# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch
tensor = torch.rand(7,7)
# Create random tensor
tensor

tensor([[0.0432, 0.2382, 0.0012, 0.7130, 0.9767, 0.8852, 0.2332],
        [0.9482, 0.6846, 0.7119, 0.2850, 0.7317, 0.8787, 0.1581],
        [0.0494, 0.7269, 0.0833, 0.8015, 0.3548, 0.8880, 0.6042],
        [0.8124, 0.4178, 0.6392, 0.0313, 0.5589, 0.0883, 0.5961],
        [0.4014, 0.1522, 0.4058, 0.8105, 0.4167, 0.1505, 0.2394],
        [0.9380, 0.8457, 0.6076, 0.3485, 0.4207, 0.8493, 0.2124],
        [0.4607, 0.9193, 0.9742, 0.8331, 0.6875, 0.8116, 0.2195]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor

# Perform matrix multiplication
tensor2 = torch.rand(1,7)
print(torch.mm(tensor,tensor2.T))
print(torch.matmul(tensor,tensor2.T))
tensor @ tensor2.T

tensor([[2.0611],
        [3.5642],
        [2.1097],
        [2.2749],
        [1.6881],
        [3.3360],
        [3.6326]])
tensor([[2.0611],
        [3.5642],
        [2.1097],
        [2.2749],
        [1.6881],
        [3.3360],
        [3.6326]])


tensor([[2.0611],
        [3.5642],
        [2.1097],
        [2.2749],
        [1.6881],
        [3.3360],
        [3.6326]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor = torch.rand(7,7)
tensor1 = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(tensor,tensor1.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.manual_seed(1234)
torch.cuda.manual_seed(1234)
torch.rand(2,2)

tensor([[0.0290, 0.4019],
        [0.2598, 0.3666]])


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
torch.mm(tensor_A,tensor_B.T)

tensor([[0.6507, 0.8198],
        [0.9139, 1.3789]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
print(torch.max(torch.mm(tensor_A,tensor_B.T)))
# Find min
print(torch.min(torch.mm(tensor_A,tensor_B.T)))

tensor(0.6091, device='cuda:0')
tensor(0.2505, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
max1= torch.argmax(torch.mm(tensor_A,tensor_B.T))
print(max1)
# Find arg min
min1 = torch.argmin(torch.mm(tensor_A,tensor_B.T))
print(min1)

tensor(1, device='cuda:0')
tensor(2, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
torch.squeeze(tensor)


# Print out tensors and their shapes
print(tensor)
print(torch.squeeze(tensor).shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([10])
