In [2]:
import torch

In [3]:
torch.manual_seed(42)
random_tensor1 = torch.rand(3, 4)
random_tensor1

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [4]:
torch.manual_seed(42)
random_tensor2 = torch.rand(3, 4)
random_tensor2

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [5]:
random_tensor1 == random_tensor2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [6]:
torch.manual_seed(42)
random_tensor1 = torch.rand(3, 4)
random_tensor1
torch.manual_seed(45)
random_tensor2 = torch.rand(3, 4)
random_tensor2
random_tensor1 == random_tensor2

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

### Device agnostic code

In [7]:
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [11]:
torch.cuda.device_count()

1

In [8]:
tesnor = torch.tensor([1, 2, 3])
tesnor, tesnor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [9]:
## move tensor to gpu if available
tesnor_on_gpu = tesnor.to(device)
tesnor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [12]:
### if tensor in in GPU, can't transform it to Numpy
tensor_back_on_cpu = tesnor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])