In [62]:
import torch
import numpy as np

In [63]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [64]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
x[0][0]

tensor([1, 2, 3])

In [66]:
x[0,0]

tensor([1, 2, 3])

In [67]:
x[0][0][0]

tensor(1)

In [68]:
x[0][0][2]

tensor(3)

In [69]:
x[0][1][1]

tensor(5)

In [70]:
x[0][2][2]

tensor(9)

In [71]:
x[:,0]

tensor([[1, 2, 3]])

In [72]:
x[:,:,1]

tensor([[2, 5, 8]])

In [73]:
x.shape

torch.Size([1, 3, 3])

In [74]:
x.size()

torch.Size([1, 3, 3])

In [75]:
x[:,1,1]

tensor([5])

In [76]:
x[0,0,:]

tensor([1, 2, 3])

In [77]:
x[0][2][2]

tensor(9)

In [78]:
x[:,2,2]

tensor([9])

In [79]:
x[:,:,2]

tensor([[3, 6, 9]])

In [80]:
x[0,2,0]

tensor(7)

In [81]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [84]:
numpy_tensor.dtype

dtype('float32')

In [85]:
tensor = tensor + 1
tensor

tensor([2., 2., 2., 2., 2., 2., 2.])

In [86]:
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)