In [21]:
import torch

In [22]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [24]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)
float_32_tensor

tensor([3., 6., 9.])

In [25]:
multiply = float_32_tensor* float_16_tensor

In [26]:
multiply

tensor([ 9., 36., 81.])

In [27]:
multiply.dtype

torch.float32

In [28]:
multiply.size()

torch.Size([3])

In [29]:
multiply.shape

torch.Size([3])

In [30]:
multiply.device

device(type='cpu')

### Manipulating Tensors

In [31]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
tensor * 10

tensor([10, 20, 30])

In [33]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [34]:
tensor - 10

tensor([-9, -8, -7])

In [35]:
tensor ** 2

tensor([1, 4, 9])

In [20]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [36]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [37]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [38]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

### Matrix Multiplication
- Element Wise
- Matrix

In [41]:
print(f"{tensor} matmul {tensor}")

tensor([1, 2, 3]) matmul tensor([1, 2, 3])


In [42]:
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
tensor @ tensor  ## matrix multiplication

tensor(14)

In [46]:
mat1 = torch.rand(3, 2)
mat1

tensor([[0.7160, 0.2316],
        [0.2418, 0.1546],
        [0.2266, 0.0069]])

In [47]:
mat2 = torch.rand(2, 3)
mat2

tensor([[0.9678, 0.6571, 0.7113],
        [0.8557, 0.8235, 0.4801]])

In [48]:
mat1 @ mat2

tensor([[0.8911, 0.6612, 0.6205],
        [0.3663, 0.2862, 0.2462],
        [0.2253, 0.1546, 0.1645]])

In [49]:
torch.matmul(mat1, mat2)

tensor([[0.8911, 0.6612, 0.6205],
        [0.3663, 0.2862, 0.2462],
        [0.2253, 0.1546, 0.1645]])

In [50]:
torch.mm(mat1, mat2)  # alias for matmul

tensor([[0.8911, 0.6612, 0.6205],
        [0.3663, 0.2862, 0.2462],
        [0.2253, 0.1546, 0.1645]])

In [51]:
tensor1 = torch.rand(3, 2)
tensor1

tensor([[0.5081, 0.8471],
        [0.3858, 0.8100],
        [0.9536, 0.8438]])

In [53]:
tensor2 = torch.rand(3, 2)
tensor2

tensor([[0.2128, 0.3961],
        [0.0298, 0.8882],
        [0.1961, 0.8073]])

In [55]:
tensor2.T

tensor([[0.2128, 0.0298, 0.1961],
        [0.3961, 0.8882, 0.8073]])

In [54]:
torch.matmul(tensor1, tensor2.T)

tensor([[0.4437, 0.7676, 0.7835],
        [0.4029, 0.7309, 0.7296],
        [0.5371, 0.7779, 0.8682]])

In [57]:
mat1 * mat2.T

tensor([[0.6929, 0.1982],
        [0.1589, 0.1273],
        [0.1612, 0.0033]])