In [1]:
import torch

In [2]:
x = torch.arange(1,1000,10)
x , x.dtype

(tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
         141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251, 261, 271,
         281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381, 391, 401, 411,
         421, 431, 441, 451, 461, 471, 481, 491, 501, 511, 521, 531, 541, 551,
         561, 571, 581, 591, 601, 611, 621, 631, 641, 651, 661, 671, 681, 691,
         701, 711, 721, 731, 741, 751, 761, 771, 781, 791, 801, 811, 821, 831,
         841, 851, 861, 871, 881, 891, 901, 911, 921, 931, 941, 951, 961, 971,
         981, 991]),
 torch.int64)

In [3]:
torch.mean(x.type(torch.float32))

tensor(496.)

In [4]:
x.type(torch.float32).mean()

tensor(496.)

In [5]:
torch.min(x)

tensor(1)

In [6]:
torch.max(x)

tensor(991)

In [7]:
torch.sum(x)

tensor(49600)

In [8]:
torch.argmin(x)

tensor(0)

In [9]:
torch.argmax(x)

tensor(99)

In [10]:
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [11]:
x.reshape(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [12]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [60]:
x.view(3,10)  ## share the same memory as original tensor

tensor([[-1.3140e+00, -5.3921e-01,  9.1484e-01,  1.4164e+00,  9.6912e-01,
          5.3484e-01, -1.1216e-01, -6.2000e-01,  2.5630e-01, -1.0566e+00],
        [-1.6948e+00,  2.1039e+00, -2.1698e-01, -8.2997e-02, -1.1416e+00,
         -6.3043e-01,  3.1790e-02, -2.6619e-01, -1.4071e+00,  5.9109e-01],
        [-1.7971e+00,  3.8089e-01, -5.9652e-01,  2.4729e-01, -7.4355e-01,
         -5.6970e-01,  9.1783e-01,  4.1646e-01, -9.5677e-01,  1.8048e-03]])

### Stacking

In [16]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
x_stacked = torch.stack([x,x,x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [21]:
x_stacked = torch.stack([x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [22]:
x_stacked = torch.hstack([x,x,x])
x_stacked

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
x_stacked = torch.vstack([x,x,x,x])
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [27]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.hstack((a,b))

tensor([1, 2, 3, 4, 5, 6])

In [39]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
c = torch.hstack((a,b))
c

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [30]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
torch.squeeze(x)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
torch.unsqueeze(x,dim=1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [46]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [45]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [47]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [48]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [49]:
y = torch.squeeze(x, 0)
y.size()


torch.Size([2, 1, 2, 1, 2])

In [50]:
y

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [51]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [52]:
y

tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])

In [53]:
y = torch.squeeze(x, (1, 2, 3))

In [54]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [56]:
y.size()

torch.Size([2, 2, 2])

In [57]:
x = torch.randn(2, 3, 5)  ## share the same memory as original tensor
x.size()
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])