In [1]:
import torch

In [3]:
y = torch.tensor([[[1,2,4]],
              [[3,45,5]]
              ])

In [4]:
y

tensor([[[ 1,  2,  4]],

        [[ 3, 45,  5]]])

In [5]:
y.shape

torch.Size([2, 1, 3])

In [6]:
y.ndim

3

In [9]:
y[1,0,1]

tensor(45)

### random tensors

In [26]:
random_tensor = torch.rand(2,2,2,2)

In [27]:
random_tensor

tensor([[[[0.0809, 0.7514],
          [0.9438, 0.3524]],

         [[0.7963, 0.5066],
          [0.0027, 0.3661]]],


        [[[0.5038, 0.6354],
          [0.0780, 0.7383]],

         [[0.5322, 0.8737],
          [0.3243, 0.3196]]]])

In [28]:
random_tensor.ndim

4

In [30]:
random_tensor.shape

torch.Size([2, 2, 2, 2])

In [38]:
random_tensor[1,0,0:1,1]

tensor([0.6354])

In [40]:
random_image_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_tensor

tensor([[[0.9381, 0.8753, 0.8284],
         [0.3512, 0.6663, 0.7385],
         [0.8442, 0.0332, 0.9306],
         ...,
         [0.4622, 0.9551, 0.6538],
         [0.1841, 0.4612, 0.9868],
         [0.6807, 0.8378, 0.0888]],

        [[0.4128, 0.4074, 0.7579],
         [0.7155, 0.8988, 0.1615],
         [0.6119, 0.6817, 0.5171],
         ...,
         [0.9752, 0.6702, 0.5712],
         [0.9720, 0.5762, 0.2468],
         [0.7347, 0.2108, 0.7254]],

        [[0.9970, 0.8212, 0.1195],
         [0.5863, 0.1404, 0.3902],
         [0.1874, 0.5502, 0.4156],
         ...,
         [0.4704, 0.6859, 0.7491],
         [0.5535, 0.6165, 0.0486],
         [0.7363, 0.8463, 0.8852]],

        ...,

        [[0.9948, 0.8310, 0.5666],
         [0.0163, 0.9989, 0.0801],
         [0.9167, 0.2758, 0.6655],
         ...,
         [0.3304, 0.9478, 0.1759],
         [0.3232, 0.2111, 0.5930],
         [0.5035, 0.7676, 0.0779]],

        [[0.5129, 0.0481, 0.6266],
         [0.1919, 0.6150, 0.8617],
         [0.

In [41]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [42]:
random_image_tensor.ndim

3

### zeros and ones

In [51]:
random_tensor = torch.rand(size=(3,4))
random_tensor
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [52]:
torch.ones(size=(3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [53]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### range

In [56]:
torch.arange(0,10).reshape(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [57]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [59]:
Arange = torch.arange(start=10,end=100,step=10)

In [60]:
Arange

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
torch.zeros_like(Arange)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
torch.zeros_like(input = Arange)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])